### ISSUE TITLE
FeedDate timezone fail

### ISSUE THREAD

**Issue by fjf2002** [flack/UniversalFeedCreator#14]
Unfortunately class FeedDate and thus RSS Feed pubDate fail at date strings with time zones.

For example, 

```php
var_dump(new FeedDate('1970-01-01 00:00:00+0200'));
```

... outputs a unixtime of 0, whereas -7200 would be correct.

A workaround of course is to pass unixtime integers instead of date strings.

**Comment by flack** [comment]
Hi,

I must say I'm not the biggest expert on date formats, but I thought in ISO 8601 there is supposed to be a `T` before the time. If I run 

```php
var_dump((new FeedDate('1970-01-01T00:00:00+0200'))->unix());
```

It gives me `7200` as a result. But you're saying `-7200` would be correct?

**Comment by flack** [comment]
maybe we should just replace that regex parsing with 

```php
$this->unix = (int) (new Datetime('1970-01-01 00:00:00+0200'))->format('U');
```

That gices the correct result and is about 50 lines less code

**Comment by flack** [comment]
@fjf2002 can you try if https://github.com/flack/UniversalFeedCreator/pull/15 fixes your issue?

**Comment by flack** [comment]
I've tested this myself now with a couple of different feeds with different date formats, and the change from #15 produces the correct result in all cases (whereas the previous code didn't, at least not for ISO 8601 dates with numeric timezones)

**Comment by fjf2002** [comment]
Dear flack,

> I must say I'm not the biggest expert on date formats, but I thought in ISO 8601 there is supposed to be a `T` before the time.

Well see https://github.com/dokuwiki/dokuwiki/issues/2960 , in particular https://github.com/dokuwiki/dokuwiki/blob/master/feed.php#L244 : RFC 2822/RFC 5322 gets used there. (Is that use case mal-using your library?)

> If I run
> ```
> var_dump((new FeedDate('1970-01-01T00:00:00+0200'))->unix());
> ```
> It gives me `7200` as a result. But you're saying `-7200` would be correct?

Yes, cf. `(new Datetime('1970-01-01 00:00:00+0200'))->format('U');` which also gives -7200 .


> maybe we should just replace that regex parsing with 
> ```php
> $this->unix = (int) (new Datetime('1970-01-01 00:00:00+0200'))->format('U');
> ```
> That gices the correct result and is about 50 lines less code

It would be absolutely preferrable to use tested libraries which not only give you 50 lines less code, but also hopefully these libraries are throughly tested.


> @fjf2002 can you try if https://github.com/flack/UniversalFeedCreator/pull/15 fixes your issue?
Yes, Thank You.

Perhaps you should also even trash the `FeedDate` class - I suppose PHP's `DateTime` can to that conversions out of the box.

**Comment by flack** [comment]
> Well see https://github.com/dokuwiki/dokuwiki/issues/2960 , in particular https://github.com/dokuwiki/dokuwiki/blob/master/feed.php#L244 : RFC 2822/RFC 5322 gets used there. (Is that use case mal-using your library?)

Well, this library was not written by me, but 20 years ago by someone name Kai Blankenhorn, I merely made it available on Packagist and fixed it so that it works with newer PHP versions, so I can't speak with absolute authority on how this was intended to be used. The code you link to looks correct to me, the diff that is in the issue you linked partially comes from #5, which hasn't caused any problems I know of in the six years since it was merged. The rest of it looks like a local modification, but I don't really know anything about DocuWiki, so I'm not sure if that's correct or not.

> It would be absolutely preferrable to use tested libraries which not only give you 50 lines less code, but also hopefully these libraries are throughly tested.

Yes, the change is merged and released now. The `DateTime` class did not yet exist when this libary was written, which I think is the only reason these 50 lines of code existed. But they're gone now, and so is the parsing error. 

> Perhaps you should also even trash the FeedDate class - I suppose PHP's DateTime can do that conversions out of the box.

Yes, it might be cleaner, but it would also break a lot of existing client code, and for now real benefit. With the recent change, the `FeedDate` class consists just of a couple of very simple convenience functions that should be pretty robust and are unlikely to change, so I'd rather keep it for now.

**Comment by fjf2002** [comment]
Thank you for your work.

> The DateTime class did not yet exist when this libary was written

Yes, I suspected that.
